#!/bin/sh
EXEC="/usr/bin/aesdsocket"

case "$1" in
    start)
    echo "Starting aesdsocket"
    start-stop-daemon --start --name $(basename $EXEC) --startas $EXEC -- -d
    ;;
    stop)
    echo "Stopping aesdsocket"
    start-stop-daemon -K -n $(basename $EXEC) -- -d
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac 

exit 0
