#!/bin/sh
EXEC="/usr/bin/aesdsocket"

module=aesdchar
device=aesdchar

setup_device () {
    mode="664"
    cd `dirname $0`
    set -e
    # Group: since distributions do it differently, look for wheel or use staff
    if grep -q '^staff:' /etc/group; then
        group="staff"
    else
        group="wheel"
    fi

    if [ -e ${module}.ko ]; then
        echo "Loading local built file ${module}.ko"
        insmod ./$module.ko $* || exit 1
    else
        echo "Local file ${module}.ko not found, attempting to modprobe"
        modprobe ${module} || exit 1
    fi
    major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
    rm -f /dev/${device}
    mknod /dev/${device} c $major 0
    chgrp $group /dev/${device}
    chmod $mode  /dev/${device}
}

clean_device () {
    cd `dirname $0`
    # invoke rmmod with all arguments we got
    rmmod $module || exit 1

    # Remove stale nodes

    rm -f /dev/${device}
}

case "$1" in
    start)
    echo "Starting aesdsocket"
    setup_device
    start-stop-daemon --start --name $(basename $EXEC) --startas $EXEC -- -d
    ;;
    stop)
    echo "Stopping aesdsocket"
    clean_device
    start-stop-daemon -K -n $(basename $EXEC) -- -d
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac 

exit 0
